// <auto-generated />
using System;
using Discord_Stream_Notify_Bot.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discord_Stream_Notify_Bot.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250320071359_RefactorDbContext")]
    partial class RefactorDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.BannerChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LastChangeStreamId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BannerChange");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.GuildConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("LogMemberStatusChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("NoticeChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("GuildConfig");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.GuildYoutubeMemberConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MemberCheckChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberCheckChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<ulong>("MemberCheckGrantRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MemberCheckVideoId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GuildYoutubeMemberConfig");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.NoticeTwitCastingStreamChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("DiscordChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("StartStreamMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NoticeTwitCastingStreamChannels");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.NoticeTwitchStreamChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeStreamDataMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("DiscordChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("EndStreamMessage")
                        .HasColumnType("longtext");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("NoticeTwitchUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("StartStreamMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NoticeTwitchStreamChannels");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.NoticeTwitterSpaceChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("DiscordChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("NoticeTwitterSpaceUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("NoticeTwitterSpaceUserScreenName")
                        .HasColumnType("longtext");

                    b.Property<string>("StratTwitterSpaceMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NoticeTwitterSpaceChannel");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.NoticeYoutubeStreamChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeTimeMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeleteMessage")
                        .HasColumnType("longtext");

                    b.Property<ulong>("DiscordNoticeStreamChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("DiscordNoticeVideoChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("EndMessage")
                        .HasColumnType("longtext");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsCreateEventForNewStream")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewStreamMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("NewVideoMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("StratMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeChannelId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NoticeYoutubeStreamChannel");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.RecordYoutubeChannel", b =>
                {
                    b.Property<string>("YoutubeChannelId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("YoutubeChannelId");

                    b.ToTable("RecordYoutubeChannel");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitCastingSpider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWarningUser")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TwitCastingSpider");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitCastingStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StreamStartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StreamSubTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("StreamTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TwitCastingStreams");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitchSpider", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWarningUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OfflineImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("UserLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("TwitchSpider");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitchStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameName")
                        .HasColumnType("longtext");

                    b.Property<string>("StreamId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StreamStartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StreamTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.Property<string>("UserLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TwitchStreams");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitterSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SpaecActualStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SpaecId")
                        .HasColumnType("longtext");

                    b.Property<string>("SpaecMasterPlaylistUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SpaecTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserScreenName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TwitterSpace");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.TwitterSpaecSpider", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWarningUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserScreenName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("TwitterSpaecSpider");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.Video", b =>
                {
                    b.Property<string>("VideoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<int>("ChannelType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoTitle")
                        .HasColumnType("longtext");

                    b.HasKey("VideoId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.YoutubeChannelNameToId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("YoutubeChannelNameToId");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.YoutubeChannelOwnedType", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<int>("ChannelType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChannelId");

                    b.ToTable("YoutubeChannelOwnedType");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.YoutubeChannelSpider", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsTrustedChannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSubscribeTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChannelId");

                    b.ToTable("YoutubeChannelSpider");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.YoutubeMemberAccessToken", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("DiscordUserId"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("longtext");

                    b.HasKey("DiscordUserId");

                    b.ToTable("YoutubeMemberAccessToken");
                });

            modelBuilder.Entity("Discord_Stream_Notify_Bot.DataBase.Table.YoutubeMemberCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckYTChannelId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastCheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("YoutubeMemberCheck");
                });
#pragma warning restore 612, 618
        }
    }
}
